# spring.application.name=authuser

server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual_creation: true
    properties:
      hibernate:
        show_sql: true